version: '{build}'
branches:  
  only:
  - master
nuget:  
  disable_publish_on_pr: true
build_script:  
- ps: .\Build.ps1
test: off

artifacts:  
- path: .\artifacts\*.nupkg
  name: NuGet

deploy:  
- provider: NuGet
  server: https://www.myget.org/F/andypook/api/v2/package
  api_key:
    secure: iykKTfD0X828Y3pLkA5jrO7tJ4wA/mfsQOrd1dBD4AR5jvdg75DxEegCa+TMGNHZ
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: master
  api_key:
    secure: T0X/J/+eUEBva83yA2IYP207+GIeT5CdwUN/0mQyW0WjS9AG+AnGIpwWjpCmNAlP
  on:
    branch: master
    appveyor_repo_tag: true
